# Base image
FROM nvidia/cudagl:11.3.0-devel-ubuntu20.04

# Setup basic packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    git \
    curl \
    vim \
    ca-certificates \
    libjpeg-dev \
    libpng-dev \
    libglfw3-dev \
    libglm-dev \
    libx11-dev \
    libomp-dev \
    libegl1-mesa-dev \
    pkg-config \
    wget \
    zip \
    mesa-utils \
    git-lfs \
    unzip &&\
    rm -rf /var/lib/apt/lists/*

# Install conda
RUN curl -L -o ~/miniconda.sh -O  https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh  &&\
    chmod +x ~/miniconda.sh &&\
    ~/miniconda.sh -b -p /opt/conda &&\
    rm ~/miniconda.sh &&\
    /opt/conda/bin/conda install numpy pyyaml scipy ipython mkl mkl-include &&\
    /opt/conda/bin/conda clean -ya
ENV PATH /opt/conda/bin:$PATH

# Install cmake
RUN wget https://github.com/Kitware/CMake/releases/download/v3.14.0/cmake-3.14.0-Linux-x86_64.sh
RUN mkdir /opt/cmake
RUN sh /cmake-3.14.0-Linux-x86_64.sh --prefix=/opt/cmake --skip-license
RUN ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake
RUN cmake --version

# Conda environment
RUN conda create -n habitat python=3.9 cmake=3.14.0 cudatoolkit=10.2
ENV LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/opt/conda/envs/habitat/lib/python3.9/site-packages/nvidia_cublas_cu11-11.10.3.66-py3.7-linux-x86_64.egg/nvidia/cublas/lib/
ENV LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/opt/conda/envs/habitat/lib/python3.9/site-packages/nvidia_cudnn_cu11-8.5.0.96-py3.7-linux-x86_64.egg/nvidia/cudnn/lib/
# Setup habitat-sim
#RUN git clone --branch stable https://github.com/facebookresearch/habitat-sim.git
#RUN /bin/bash -c ". activate habitat; cd habitat-sim; pip install -e ."
RUN /bin/bash -c ". activate habitat; conda install -y habitat-sim=0.3.0 withbullet -c conda-forge -c aihabitat"
# Install challenge specific habitat-lab
RUN git clone https://github.com/tribhi/habitat-lab.git
RUN /bin/bash -c ". activate habitat; cd habitat-lab; pip install -e habitat-lab"
RUN /bin/bash -c ". activate habitat; conda install -y pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia"
#RUN /bin/bash -c ". activate habitat; pip install -y -e habitat-lab; pip install -y -e habitat-baselines"

# Silence habitat-sim logs
ENV GLOG_minloglevel=2
ENV MAGNUM_LOG="quiet"

